# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: actions/checkout@v2
      - run: ./init.sh blank
      - name: Dockerize
        run: |
          chmod +x dockerize.sh
          ./dockerize.sh
          docker save -o save.artifact iolabs/blank
      - name: Publish
        run: |
          curl -X POST https://io-labs.fr/release-deploy/api/projects/5caf6b8023a8461c7f0300bc/versions?privatetoken=V5Yx-SbyRMn9ZVDpjS6d --data-binary "@save.artifact" -H "Content-Type: application/json"
          curl -X POST https://io-labs.fr/release-deploy/api/projects/5caf6b8023a8461c7f0300bc/actions/deploy?label=latest\&privatetoken=V5Yx-SbyRMn9ZVDpjS6d -H "Content-Type: application/json"
